INSERT INTO MINERAL (name) VALUES ('Eisen');
INSERT INTO MINERAL (name) VALUES ('Selen');
INSERT INTO MINERAL (name) VALUES ('Mangan');
INSERT INTO MINERAL (name) VALUES ('Jod');

INSERT INTO MINERAL_RECOMMENDATION ( MAX_AMOUNT, MIN_AMOUNT, UNIT, TIME_PERIOD_DIMENSION, TIME_PERIOD_LENGTH, MINERAL_ID) VALUES (11, 1, 'mg', 'HOURS', 1, 1);
INSERT INTO MINERAL_RECOMMENDATION ( MAX_AMOUNT, MIN_AMOUNT, UNIT, TIME_PERIOD_DIMENSION, TIME_PERIOD_LENGTH, MINERAL_ID) VALUES (22, 2, 'µg', 'DAYS', 2, 2);

INSERT INTO FOOD (NAME) VALUES ('Fenchel');
INSERT INTO FOOD (NAME) VALUES ('Paprika');

INSERT INTO AMOUNT_CONTAINED (AMOUNT, UNIT, FOOD_ID, MINERAL_ID) VALUES (10,'mg', 1,1);
INSERT INTO AMOUNT_CONTAINED (AMOUNT, UNIT, FOOD_ID, MINERAL_ID) VALUES (20,'g', 1,2);
INSERT INTO AMOUNT_CONTAINED (AMOUNT, UNIT, FOOD_ID, MINERAL_ID) VALUES (20,'mg', 2,2);