INSERT INTO MINERAL (name) VALUES ('Eisen');
INSERT INTO MINERAL (name) VALUES ('Selen');
INSERT INTO MINERAL (name) VALUES ('Mangan');
INSERT INTO MINERAL (name) VALUES ('Jod');

INSERT INTO MINERAL_RECOMMENDATION ( ID , MxX_AMOUNT, MIN_AMOUNT, UNIT, TIME_PERIOD_DIMENSION, TIME_PERIOD_LENGTH, MINERAL_ID) VALUES (1,11, 1, 'mg', 'HOURS', 1, 1);
INSERT INTO MINERAL_RECOMMENDATION ( ID , MAX_AMOUNT, MIN_AMOUNT, UNIT, TIME_PERIOD_DIMENSION, TIME_PERIOD_LENGTH, MINERAL_ID) VALUES (2,22, 2, 'µg', 'DAYS', 2, 2);

INSERT INTO FOOD (ID, NAME) VALUES (1, 'Fenchel');
INSERT INTO FOOD (ID, NAME) VALUES (2, 'Paprika');

INSERT INTO AMOUNT_CONTAINED (ID, AMOUNT, UNIT, FOOD_ID, MINERAL_ID) VALUES (1,10,'mg', 1,1);
INSERT INTO AMOUNT_CONTAINED (ID, AMOUNT, UNIT, FOOD_ID, MINERAL_ID) VALUES (2,10,'mg', 1,1);